# Run the integration test "background-task-tests" against the 'pre-alpha' stack.

runner.log-level = "DEBUG"
runner.logging = false
runner.no-setup = false
runner.no-teardown = false
runner.enforce-single-threaded=true

domain.scylla-env-file = "pre-alpha.env"

[domain.origin]
scheme = "http"
port = 20724
host = { RegName = "indiemark.local" }

[domain.scylla]
hosts = ["127.0.0.1:9052"]
translations=[["172.14.0.3:9052", "127.0.0.1:9053"], ["172.14.0.4:9052", "127.0.0.1:9054"]]

[domain.dynamo]
location = ["http://127.0.0.1:8052", "http://127.0.0.1:8053", "http://127.0.0.1:8054"]
