# Run the integration test "cache-tests" against a completely
# different ScyllaDB/indielinksd stack than the default. This can be
# handy for working in two git worktrees simultaneously. This is
# intended for use in the "bugfix" worktree.

runner.log-level = "DEBUG"
runner.logging = false
runner.no-setup = false
runner.no-teardown = false
runner.enforce-single-threaded=true

domain.indielinks = "http://indiemark.local:20675"
domain.ops = "http://localhost:20710"
domain.scylla-env-file = "bugfix.env"
domain.local-state-base = "/tmp/indielinksd-bugfix-"
domain.alternator-config-base ="../conf/bugfix/indielinksd-alternator-"
domain.scylla-config-base = "../conf/bugfix/indielinksd-scylla-"
domain.haproxy-id = "bugfix"
domain.haproxy-port = 20675

[domain.raft-nodes]
"0" = { addr = "127.0.0.1:20711" }
"1" = { addr = "127.0.0.1:20714" }
"2" = { addr = "127.0.0.1:20717" }
"3" = { addr = "127.0.0.1:20720" }
"4" = { addr = "127.0.0.1:20723" }

[domain.scylla]
hosts = ["127.0.0.1:9049"]
translations=[["172.13.0.3:9049", "127.0.0.1:9050"], ["172.13.0.4:9049", "127.0.0.1:9051"]]

[domain.dynamo]
location = ["http://127.0.0.1:8049", "http://127.0.0.1:8050", "http://127.0.0.1:8051"]
