# Run the integration test "cache-tests" against a completely
# different ScyllaDB/indielinksd stack than the default. This can be
# handy for working in two git worktrees simultaneously. It's named
# "front-end" because that was the first git worktree in which I
# wanted a separate stack.

# development variant-- turn on logging & don't teardown the fixture afterwards

runner.log-level = "DEBUG"
runner.logging = true
runner.no-setup = false
runner.no-teardown = true
runner.enforce-single-threaded=true

domain.indielinks = "http://indiemark.local:20674"
domain.ops = "http://localhost:20695"
domain.scylla-env-file = "front-end.env"
domain.local-state-base = "/tmp/indielinksd-front-end-"
domain.alternator-config-base ="../conf/front-end/indielinksd-alternator-"
domain.scylla-config-base = "../conf/front-end/indielinksd-scylla-"
domain.haproxy-id = "front-end"
domain.haproxy-port = 20674

[domain.raft-nodes]
"0" = { addr = "127.0.0.1:20696" }
"1" = { addr = "127.0.0.1:20699" }
"2" = { addr = "127.0.0.1:20702" }
"3" = { addr = "127.0.0.1:20705" }
"4" = { addr = "127.0.0.1:20708" }

[domain.scylla]
hosts = ["127.0.0.1:9046"]
translations=[["172.12.0.3:9046", "127.0.0.1:9047"], ["172.12.0.4:9046", "127.0.0.1:9048"]]

[domain.dynamo]
location = ["http://127.0.0.1:8046", "http://127.0.0.1:8047", "http://127.0.0.1:8048"]
