# Run the integration test "cache-tests" against the 'pre-alpha' stack.
# This configuration is meant for debugging-- turn on logging & don't
# teardown the test fixture on completion (to enable inspection of
# logs &c)

runner.log-level = "DEBUG"
runner.logging = true
runner.no-setup = false
runner.no-teardown = true
runner.enforce-single-threaded=true

domain.indielinks = "http://indiemark.local:20739"
domain.ops = "http://localhost:20725"
domain.scylla-env-file = "pre-alpha.env"
domain.local-state-base = "/tmp/indielinksd-pre-alpha-"
domain.alternator-config-base = "../conf/pre-alpha/indielinksd-alternator-"
domain.scylla-config-base = "../conf/pre-alpha/indielinksd-scylla-"
domain.haproxy-id = "pre-alpha"
domain.haproxy-port = 20739

[domain.raft-nodes]
"0" = { addr = "127.0.0.1:20726" }
"1" = { addr = "127.0.0.1:20729" }
"2" = { addr = "127.0.0.1:20732" }
"3" = { addr = "127.0.0.1:20735" }
"4" = { addr = "127.0.0.1:20738" }

[domain.scylla]
hosts = ["127.0.0.1:9052"]
translations=[["172.14.0.3:9052", "127.0.0.1:9053"], ["172.14.0.4:9052", "127.0.0.1:9054"]]

[domain.dynamo]
location = ["http://127.0.0.1:8052", "http://127.0.0.1:8053", "http://127.0.0.1:8054"]
