# Run the integration test suite against a completely different
# ScyllaDB/indielinksd stack than the default. This can be handy for
# working in two git worktrees simultaneously. It's named "front-end"
# because that was the first git worktree in which I wanted a separate
# stack.

runner.log-level = "DEBUG"
runner.logging = false
runner.no-setup = false
runner.no-teardown = false
runner.enforce-single-threaded=true

domain.local-state-dir = "/tmp/indielinks-front-end"
domain.indielinks-alternator-config-file = "indielinksd-front-end-alternator.toml"
domain.indielinks-scylla-config-file = "indielinksd-front-end-scylla.toml"
domain.username = "sp1ff"
# The URL at which indielinks can be reached from *within* a test'
domain.indielinks = "http://indiemark.local:20694"
domain.ops = "http://localhost:20695"
domain.grpc = "127.0.0.1:20696"
domain.api-key = "v1:5eb56ceebb7425aafe36eabca8b923054b4907d9375acd0b9950c51b57b201fb73e437428050f451b57632f99a3bbd5bed1c0f51cc0df752147090ed26e975f4"
domain.scylla-env-file = "../infra/front-end.env"

# Regrettably, this must match exactly the indielinks configuration item of the same name
[domain.pepper.peppers]
"pepper-ver:20250213" = [0xb2, 0x91, 0x48, 0x34, 0x4d, 0x5f, 0xd3, 0x7e, 0x59, 0x71, 0x57, 0x91, 0xdd, 0x00, 0x32, 0x92, 0x62, 0xe9, 0x19, 0x77, 0x6d, 0xae, 0x4b, 0x5b, 0x6a, 0xab, 0x00, 0x67, 0x0e, 0x8c, 0xf4, 54]

[domain.scylla]
hosts = ["127.0.0.1:9046"]
translations=[["172.12.0.3:9046", "127.0.0.1:9044"], ["172.12.0.4:9046", "127.0.0.1:9045"]]

[domain.dynamo]
location = ["http://127.0.0.1:8046", "http://127.0.0.1:8047", "http://127.0.0.1:8048"]
