# Run the integration test "smoke-tests" against a completely
# different ScyllaDB/indielinksd stack than the default. This can be
# handy for working in two git worktrees simultaneously. It's named
# "bugfix" because it's intended for use in the bugfix worktree.

runner.log-level = "DEBUG"
runner.logging = true
runner.no-setup = false
runner.no-teardown = true
runner.enforce-single-threaded=true

domain.single-node.indielinks = "http://indiemark.local:20709"
domain.single-node.ops = "http://localhost:20710"
domain.single-node.grpc = "127.0.0.1:20711"
# This needs to agree with the `log-file` item in `indielinksd-pre-alpha-{alternator,scylla}.toml`
domain.single-node.local-state-dir = "/tmp/indielinks-bugfix"
domain.single-node.indielinks-alternator-config-file = "indielinksd-bugfix-alternator.toml"
domain.single-node.indielinks-scylla-config-file = "indielinksd-bugfix-scylla.toml"

# This needs to aggree with the `log-file` item in `indielinksd-{alternator,scylla}-{0,1,2,3,4}.toml`
domain.clustered.cluster-local-state-base = "/tmp/indielinksd-bugfix-"
domain.clustered.indielinks-scylla-cluster-config-base = "../conf/bugfix/indielinksd-scylla-"
domain.clustered.indielinks-alternator-cluster-config-base = "../conf/bugfix/indielinksd-alternator-"
domain.clustered.nodes = [["http://indiemark.local:20709", "http://127.0.0.1:20710", "127.0.0.1:20711"],
                          ["http://indiemark.local:20712", "http://127.0.0.1:20713", "127.0.0.1:20714"],
                          ["http://indiemark.local:20715", "http://127.0.0.1:20716", "127.0.0.1:20717"]]
domain.clustered.cluster-size = 3
domain.clustered.haproxy-id = 2
domain.clustered.haproxy-port = 20675

domain.username = "sp1ff"
# The URL at which indielinks can be reached from *within* a test'
domain.api-key = "v1:5eb56ceebb7425aafe36eabca8b923054b4907d9375acd0b9950c51b57b201fb73e437428050f451b57632f99a3bbd5bed1c0f51cc0df752147090ed26e975f4"
domain.scylla-env-file = "bugfix.env"

# Regrettably, this must match exactly the indielinks configuration item of the same name
[domain.pepper.peppers]
"pepper-ver:20250213" = [0xb2, 0x91, 0x48, 0x34, 0x4d, 0x5f, 0xd3, 0x7e, 0x59, 0x71, 0x57, 0x91, 0xdd, 0x00, 0x32, 0x92, 0x62, 0xe9, 0x19, 0x77, 0x6d, 0xae, 0x4b, 0x5b, 0x6a, 0xab, 0x00, 0x67, 0x0e, 0x8c, 0xf4, 54]

[domain.scylla]
hosts = ["127.0.0.1:9049"]
translations=[["172.13.0.2:9049", "127.0.0.1:9050"], ["172.13.0.3:9049", "127.0.0.1:9050"], ["172.13.0.4:9049", "127.0.0.1:9051"]]

[domain.dynamo]
location = ["http://127.0.0.1:8049", "http://127.0.0.1:8050", "http://127.0.0.1:8051"]
