# `smoke-tests` configuration suitable for development.
# Assumes you've run `../../infra/scylla-up` and are
# somehow running a development build of indielinks (with
# the public endpoint at localhost:20679).

runner.log-level = "DEBUG"
runner.logging = true
runner.no-setup = false
runner.no-teardown = true
runner.enforce-single-threaded=true

domain.single-node.indielinks = "http://indiemark.local:20724"
domain.single-node.ops = "http://localhost:20725"
domain.single-node.grpc = "127.0.0.1:20726"
# This needs to agree with the `log-file` item in `indielinksd-pre-alpha-{alternator,scylla}.toml`
domain.single-node.local-state-dir = "/tmp/indielinks-pre-alpha"
domain.single-node.indielinks-alternator-config-file = "indielinksd-pre-alpha-alternator.toml"
domain.single-node.indielinks-scylla-config-file = "indielinksd-pre-alpha-scylla.toml"

# This needs to aggree with the `log-file` item in `indielinksd-{alternator,scylla}-{0,1,2,3,4}.toml`
domain.clustered.indielinks-scylla-cluster-config-base = "../conf/pre-alpha/indielinksd-scylla-"
domain.clustered.indielinks-alternator-cluster-config-base = "../conf/pre-alpha/indielinksd-alternator-"
domain.clustered.nodes = [["http://indiemark.local:20724", "http://127.0.0.1:20725", "127.0.0.1:20726"],
                          ["http://indiemark.local:20727", "http://127.0.0.1:20728", "127.0.0.1:20729"],
                          ["http://indiemark.local:20730", "http://127.0.0.1:20731", "127.0.0.1:20732"]]
domain.clustered.cluster-size = 3
domain.clustered.haproxy-id = 3
domain.clustered.haproxy-port = 20739
# This needs to aggree with the `log-file` item in `indielinksd-{alternator,scylla}-{0,1,2,3,4}.toml`
domain.clustered.cluster-local-state-base = "/tmp/indielinksd-pre-alpha-"

domain.scylla-env-file = "pre-alpha.env"
domain.username = "sp1ff"
domain.api-key = "v1:5eb56ceebb7425aafe36eabca8b923054b4907d9375acd0b9950c51b57b201fb73e437428050f451b57632f99a3bbd5bed1c0f51cc0df752147090ed26e975f4"

# Regrettably, this must match exactly the indielinks configuration item of the same name
[domain.pepper.peppers]
"pepper-ver:20250213" = [0xb2, 0x91, 0x48, 0x34, 0x4d, 0x5f, 0xd3, 0x7e, 0x59, 0x71, 0x57, 0x91, 0xdd, 0x00, 0x32, 0x92, 0x62, 0xe9, 0x19, 0x77, 0x6d, 0xae, 0x4b, 0x5b, 0x6a, 0xab, 0x00, 0x67, 0x0e, 0x8c, 0xf4, 54]

[domain.scylla]
hosts = ["127.0.0.1:9052"]
translations=[["172.14.0.2:9052", "127.0.0.1:9052"], ["172.14.0.3:9052", "127.0.0.1:9053"], ["172.14.0.4:9052", "127.0.0.1:9054"]]

[domain.dynamo]
location = ["http://127.0.0.1:8052", "http://127.0.0.1:8053", "http://127.0.0.1:8054"]
