[domain]
api-key = "v1:5eb56ceebb7425aafe36eabca8b923054b4907d9375acd0b9950c51b57b201fb73e437428050f451b57632f99a3bbd5bed1c0f51cc0df752147090ed26e975f4"
scylla-env-file = "bugfix.env"
username = "sp1ff"

[domain.clustered]
cluster-local-state-base = "/tmp/indielinksd-bugfix-"
cluster-size = 3
haproxy-id = 1
haproxy-port = 20675
indielinks-alternator-cluster-config-base = "../target/conf/bugfix/indielinksd-alternator-"
indielinks-scylla-cluster-config-base = "../target/conf/bugfix/indielinksd-scylla-"
nodes = [
    [
    "http://indiemark.local:20709",
    "http://127.0.0.1:20710",
    "127.0.0.1:20711",
],
    [
    "http://indiemark.local:20712",
    "http://127.0.0.1:20713",
    "127.0.0.1:20714",
],
    [
    "http://indiemark.local:20715",
    "http://127.0.0.1:20716",
    "127.0.0.1:20717",
],
]

[domain.dynamo]
location = [
    "http://127.0.0.1:8049",
    "http://127.0.0.1:8050",
    "http://127.0.0.1:8051",
]

[domain.pepper.peppers]
"pepper-ver:20250213" = [
    178,
    145,
    72,
    52,
    77,
    95,
    211,
    126,
    89,
    113,
    87,
    145,
    221,
    0,
    50,
    146,
    98,
    233,
    25,
    119,
    109,
    174,
    75,
    91,
    106,
    171,
    0,
    103,
    14,
    140,
    244,
    54,
]

[domain.scylla]
hosts = ["127.0.0.1:9049"]
translations = [
    [
    "172.13.0.2:9049",
    "127.0.0.1:9049",
],
    [
    "172.13.0.3:9049",
    "127.0.0.1:9050",
],
    [
    "172.13.0.4:9049",
    "127.0.0.1:9051",
],
]

[domain.single-node]
grpc = "127.0.0.1:20711"
indielinks = "http://indiemark.local:20709"
indielinks-alternator-config-file = "../target/conf/bugfix/indielinksd-bugfix-alternator.toml"
indielinks-scylla-config-file = "../target/conf/bugfix/indielinksd-bugfix-scylla.toml"
local-state-dir = "/tmp/indielinks-bugfix/"
ops = "http://localhost:20710"

[runner]
enforce-single-threaded = true
log-level = "DEBUG"
logging = true
no-setup = false
no-teardown = true
