[package]
name = "indielinks-cache"
version = "0.0.1"
edition = "2024"

[dependencies]
async-trait = { workspace = true }
chrono = { workspace = true }
futures = { workspace = true }
indielinks-shared = { workspace = true }
itertools = { workspace = true }
lru = { workspace = true }
non-zero = { workspace = true }
nonempty-collections = { workspace = true, features = ["serde"] }
nonzero = { workspace = true }
openraft = { workspace = true, features = ["serde", "storage-v2"] }
reqwest = { workspace = true, features = ["json"] }
serde = { workspace = true }
serde_json = { workspace = true }
snafu = { workspace = true, features = ["backtrace"] }
tap = { workspace = true }
tokio = { workspace = true, features = ["time"] }
tracing = { workspace = true }
typenum = { workspace = true }
url = { workspace = true }
uuid = { workspace = true, features = ["v4"] }
xxhash-rust = { workspace = true, features = ["xxh64"] }

[dev-dependencies]
test-log = { workspace = true, features = ["trace"] }
