[package]
name = "indielinks"
version = "0.0.1"
edition = "2021"
license-file = "../COPYING"
description = "Social bookmarking in the Fediverse"

[dependencies]
ammonia = { workspace = true }
approx = { workspace = true }
argon2 = { workspace = true, features = ["password-hash", "std"] }
askama = { workspace = true, features = ["code-in-doc"] }
async-stream = { workspace = true }
async-trait = { workspace = true }
atom_syndication = { workspace = true, features = ["with-serde"] }
aws-config = { workspace = true, features = ["behavior-version-latest"] }
aws-sdk-dynamodb = { workspace = true }
aws-sdk-ssm = { workspace = true }
aws-smithy-async = { workspace = true, features = ["rt-tokio"] }
aws-smithy-runtime-api = { workspace = true, features = ["client"] }
axum = { workspace = true, features = ["macros", "tracing"] }
axum-accept = { workspace = true }
axum-extra = { workspace = true, features = ["cookie", "query", "typed-header"] }
base64 = { workspace = true }
bytes = { workspace = true }
chacha20poly1305 = { workspace = true, features = ["std"] }
chrono = { workspace = true, features = ["serde"] }
clap = { workspace = true, features = ["cargo", "env"] }
comrak = { workspace = true }
crypto-common = { workspace = true }
dashmap = { workspace = true }
either = { workspace = true, features = ["serde"] }
enum-map = { workspace = true }
errno = { workspace = true }
form_urlencoded = { workspace = true }
futures = { workspace = true }
governor = { workspace = true }
hex = { workspace = true }
hkdf = { workspace = true, features = ["std"] }
hmac = { workspace = true }
home = { workspace = true }
http = { workspace = true }
http-serde = { workspace = true }
indielinks-cache = { workspace = true }
indielinks-shared = { workspace = true, features = ["backend", "__internal"] }
inventory = { workspace = true }
itertools = { workspace = true }
jwt = { workspace = true }
keyed_priority_queue = { workspace = true }
lazy_static = { workspace = true }
libc = { workspace = true }
lru = { workspace = true }
lz4_flex = { workspace = true } # RUSTSEC-2026-0041
nonempty-collections = { workspace = true, features = ["serde"] }
nonzero = { workspace = true }
num-bigint = { workspace = true, features = ["serde"] }
openraft = { workspace = true, features = ["serde", "storage-v2"] }
opentelemetry = { workspace = true, features = ["metrics"] }
opentelemetry-otlp = { workspace = true, features = ["metrics", "http-proto", "reqwest-blocking-client"] }
opentelemetry-prometheus-text-exporter = { workspace = true }
opentelemetry_sdk = { workspace = true }
ordered-float = { workspace = true, features = ["libm", "serde"] }
password-hash = { workspace = true }
pct-str = { workspace = true }
picky = { workspace = true }
pin-project = { workspace = true }
pkcs8 = { workspace = true }
prost = { workspace = true }
rand = { workspace = true }
regex = { workspace = true }
reqwest = { workspace = true, features = ["json"] }
reqwest-retry = { workspace = true }
rmp-serde = { workspace = true }
rmpv = { workspace = true, features = ["serde", "serde_bytes", "with-serde"] }
rsa = { workspace = true }
scylla = { workspace = true, features = ["full-serialization"] }
secrecy = { workspace = true, features = ["serde"] }
serde = { workspace = true, features = ["derive"] }
serde_bytes = { workspace = true, features = ["alloc"] }
serde_dynamo = { workspace = true, features = ["aws-sdk-dynamodb+1"] }
serde_json = { workspace = true }
serde_urlencoded = { workspace = true }
sha2 = { workspace = true }
snafu = { workspace = true }
tap = { workspace = true }
tempfile = { workspace = true }
time = { workspace = true } # RUSTSEC-2026-0009
tokio = { workspace = true, features = ["rt-multi-thread", "signal", "sync"] }
toml = { workspace = true }
tonic = { workspace = true }
tower = { workspace = true, features = ["retry"] }
tower-gcra = { workspace = true }
tower-http = { workspace = true, features = ["auth", "cors", "request-id", "set-header", "trace"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter", "json"] }
unicode-segmentation = { workspace = true }
url = { workspace = true, features = ["serde"] }
uuid = { workspace = true, features = ["serde"] }
zxcvbn = { workspace = true }

[build-dependencies]
nickel-lang = { workspace = true }
prost-build = { workspace = true }
tonic-build = { workspace = true }

[dev-dependencies]
wiremock = { workspace = true }

[package.metadata.deb]
copyright = "Copyright (C) 2024-2025 Michael Herstine"
depends = ["libssl-dev", "adduser", "acl"]
maintainer = "Michael Herstine <sp1ff@pobox.com>"
maintainer-scripts = "../admin/debian/deb-maintainer-scripts"
assets = [
       ["target/release/indielinksd", "/usr/bin/", "755"],
       ["target/release/indielinks-schemas", "/usr/bin/", "755"],
       ["target/release/indic", "/usr/bin/", "755"],
       ["../conf/indielinks-deb.toml", "/etc/indielinks.toml", "644"],
       ["../scripts/indielinks-post-install", "/usr/bin/indielinks-post-install", "755"],
       ["../scripts/indielinks-ctl", "/usr/bin/indielinks-ctl", "755"],
       ["../indielinks-fe/dist/index.html", "/usr/share/indielinks/assets/index.html", "644"],
       ["../indielinks-fe/dist/indielinks-fe.js", "/usr/share/indielinks/assets/indielinks-fe.js", "644"],
       ["../indielinks-fe/dist/style.css", "/usr/share/indielinks/assets/style.css", "644"],
       ["../indielinks-fe/dist/indielinks-fe.wasm", "/usr/share/indielinks/assets/indielinks-fe.wasm", "644"],

]
# indielinks requries a post-installation script to be run by the
# operator before it can startup. If using stystemd, enable the unit,
# but don't start it.
systemd-units = { unit-name="indielinks", enable=true, start=false }
