#!/usr/bin/env bash

token="$1"
# Add some posts for test user `sp1ff`
curl -s -H "Authorization: Bearer ${token}" 'http://localhost:20679/api/v1/posts/add?url=https://instapundit.com&description=Instapundit&shared=true&tags=blog,glenn-reynolds&toread=true'
curl -s -H "Authorization: Bearer ${token}" 'http://localhost:20679/api/v1/posts/add?url=https://wsj.com&description=The%20Wall%20Street%20Journal&shared=true&tags=business&toread=true'
curl -s -H "Authorization: Bearer ${token}" 'http://localhost:20679/api/v1/posts/add?url=https://graydon2.dreamwidth.org/307291.html&description=The%20Rust%20I%20Wanted%20Had%20No%20Future&tags=rust,and,a,lot,of,tags,a,b,c,d,e,f,g,h,i,j,k&toread=true'
curl -s -H "Authorization: Bearer ${token}" 'http://localhost:20679/api/v1/posts/add?url=https://sachachua.com/blog/2025/05/working-on-the-plumbing-in-a-small-web-community/&description=Working%20on%20the%20plumbing%20in%20a%20small%20web%20community%20%3A%3A%20Sacha%20Chua&shared=true&tags=sacha,emacs,weekend&toread=true'
curl -s -H "Authorization: Bearer ${token}" 'http://localhost:20679/api/v1/posts/add?url=https://blog.polybdenum.com/2025/03/26/why-you-need-subtyping.html&description=Why%20You%20Need%20Subtyping%20%7C%20Considerations%20on%20Codecrafting&shared=true&tags=type-theory&toread=true'
curl -s -H "Authorization: Bearer ${token}" 'http://localhost:20679/api/v1/posts/add?url=https://www.racket.news/p/one-more-wafer-thin-mint&description=One%20More%20Wafer%20Thin%20Mint%3F%20-%20by%20Eric%20Salzman%20-%20Racket%20News&shared=true&tags=bonds,@weekend&toread=true'
curl -s -H "Authorization: Bearer ${token}" 'http://localhost:20679/api/v1/posts/add?url=https://commonreader.wustl.edu/c/whos-afraid-of-tom-wolfe/&description=Who%E2%80%99s%20Afraid%20of%20Tom%20Wolfe%3F%20-%20Common%20Reader&shared=true&tags=reading,tom-wolfe,history&toread=true'
