#!/usr/bin/env bash
VERSION=0.0.1

set -euo pipefail

help=
nargs=0
num_polls=120 # generous limit of two minutes
prev_option=
verbose=
version=
for option
do
    # If the previous option required an argument, assign it now.
    if test -n "$prev_option"; then
        eval $prev_option=\$option
        prev_option=
        nargs=$(($nargs+1))
        continue
    fi

    # Parse out the argument option in $option, if present.
    case $option in
        *=?*) optarg=$(expr "X$option" : '[^=]*=\(.*\)') ;;
        *=)   optarg= ;;
        *)    optarg=yes ;;
    esac

    # Options are handled here:
    case $option in
        -N | --num-polls | --num-checks)
            nargs=$(($nargs+1));
            prev_option=num_polls;;
        -N=* | --num-polls=* | --num-checks=*)
            nargs=$(($nargs+1));
            num_polls=$optarg;;
        -h | --he | --hel | --help)
	        nargs=$(($nargs+1));
            help=yes;;
        -v | --verb | --verbose)
	        nargs=$(($nargs+1));
            verbose=yes;;
        -V | --vers | --version)
	        nargs=$(($nargs+1));
            version=yes;;
        -*)
            cat >&2 <<EOF
Unrecognized option '$option'.
Try 'cache-tests-cluster-up --help' for more information.
EOF
            exit 2;;
	    *)
	        # $@ now contains the arguments, $# the number of arguments
	        shift $nargs;
	        break;;
    esac

done

if test -n "${help}"; then
    cat <<EOF
'$0' -- USAGE MESSAGE HERE

Usage:

    $0 [OPTION...] ARGUMENT...

Options:

    -h, --help      Print this message & exit
    -V, --version   Print this script's version & exit
    -v, --verbose   Produce prolix output

    -N NUM, --num-polls=N  Specify the number of one second
                    interval polls of the indielinks /healthcheck
                    endpoint before determining the build didn't
                    come up. Default: 120 (it's long to account
                    for the possiblity of building the binary)
EOF
    exit 0
fi

if test -n "${version}"; then
    cat <<EOF
cache-test-cluster-up $VERSION
EOF
    exit 0
fi

if test -n "${verbose}"; then
    set -x
fi

function hc() {
    local bin="$1"
    local port="$2"
    local log="$3"
    # curl can fail if the server isn't up, yet
    local status=$(curl -s http://localhost:${port}/healthcheck || true)
    local ntries=1
    while [ "${status}" != "GOOD" ]; do
        sleep 1.0
        status=$(curl -s http://localhost:${port}/healthcheck || true)
        ntries=$(($ntries+1))
        if [ ${ntries} -gt ${num_polls} ]; then
            echo "${bin}:${port} failed to come up; log file follows on stdout:" >&2
            ls -l "$log" || true
            cat "$log"
            echo "=== end stdout =="
            echo "ps & netstat output:"
            ps aux|grep -F "$bin"|grep -v grep
            sudo netstat -lpent|grep -F "$port"|grep -v grep
            return "1"
        fi
    done
    return "0"
}

if [ $# -ne 2 ]; then
    echo "Invoke as 'cache-test-cluster-up [in-memory|on-disk] PORT'" >&2
    exit 2
fi
bin="$1"
base_port="$2"

here=$(dirname $(realpath $0))
cd $here/../tests-indielinks-cache

if [ "${bin}" == "on-disk" ]; then
    # Create the state directories for each node
    mkdir /tmp/on-disk-node-0
    mkdir /tmp/on-disk-node-1
    mkdir /tmp/on-disk-node-2
    mkdir /tmp/on-disk-node-3
    mkdir /tmp/on-disk-node-4
fi

# Ensure that they're built, so that we don't timeout below, waiting for the build
cargo build --bin=in-memory
cargo build --bin=on-disk

# Stand-up a five node cluster. If I don't place each `cargo run` invocation
# into a sub-shell, `Command::output()` hangs.
(RUST_BACKTRACE=1 RUST_LOG=debug cargo run --bin "${bin}" -- -c 0 127.0.0.1:${base_port})      > n0.log 2>&1 < /dev/null &
(RUST_BACKTRACE=1 RUST_LOG=debug cargo run --bin "${bin}" -- -c 1 127.0.0.1:$(($base_port+1))) > n1.log 2>&1 < /dev/null &
(RUST_BACKTRACE=1 RUST_LOG=debug cargo run --bin "${bin}" -- -c 2 127.0.0.1:$(($base_port+2))) > n2.log 2>&1 < /dev/null &
(RUST_BACKTRACE=1 RUST_LOG=debug cargo run --bin "${bin}" -- -c 3 127.0.0.1:$(($base_port+3))) > n3.log 2>&1 < /dev/null &
(RUST_BACKTRACE=1 RUST_LOG=debug cargo run --bin "${bin}" -- -c 4 127.0.0.1:$(($base_port+4))) > n4.log 2>&1 < /dev/null &

# Now healthcheck each instance
hc "${bin}" ${base_port}      n0.log
hc "${bin}" $(($base_port+1)) n1.log
hc "${bin}" $(($base_port+2)) n2.log
hc "${bin}" $(($base_port+3)) n3.log
hc "${bin}" $(($base_port+4)) n4.log

# Note that we do *not* initialize the Raft cluster-- leave that for the integration tests.

exit 0
