#!/usr/bin/env bash

function hc() {
    local port=$1
    # curl can fail if the server isn't up, yet
    set +e
    status=$(curl -s http://localhost:${port}/healthcheck)
    set -e
    ntries=1
    while [ "${status}" != "GOOD" ]; do
        sleep 1.0
        set +e
        status=$(curl -s http://localhost:${port}/healthcheck)
        set -e
        ntries=$(($ntries+1))
        # Give this a few minutes (!) since we're potentially building in a subshell
        if [ ${ntries} -gt 120 ]; then
            echo "indielinks failed to come up on port ${port}" >&2
            return "1"
        fi
    done
    return "0"
}

if [ $# -ne 2 ]; then
    echo "Invoke as 'indielinks-cluster-up CONFIG-FILE-BASE-NAME' 3|5" >&2
    exit 2
fi

config="$1"
nodes="$2"
rust_log="debug,tower=info,h2=info,tower_http=info,aws_smithy_runtime=info,aws_sdk_dynamodb=info,hyper_util=info,openraft=info"

set -ex

[ -d /tmp/indielinksd-0 ] || mkdir /tmp/indielinksd-0
[ -d /tmp/indielinksd-1 ] || mkdir /tmp/indielinksd-1
[ -d /tmp/indielinksd-2 ] || mkdir /tmp/indielinksd-2
if [ "${nodes}" == "5" ]; then
    [ -d /tmp/indielinksd-3 ] || mkdir /tmp/indielinksd-3
    [ -d /tmp/indielinksd-4 ] || mkdir /tmp/indielinksd-4
fi

here=$(dirname $(realpath $0))
cd $here/../indielinks

# Run five copies of the `indielinksd` daemon. If I don't place each `cargo run` invocation
# into a sub-shell, `Command::output()` hangs.
(RUST_BACKTRACE=1 RUST_LOG="${rust_log}" cargo run --bin indielinksd -- -D -p -L /tmp/indielinksd-0 -c ${here}/../conf/${config}-0.toml) > /tmp/indielinksd-0/stdout.log 2>&1 < /dev/null &
(RUST_BACKTRACE=1 RUST_LOG="${rust_log}" cargo run --bin indielinksd -- -D -p -L /tmp/indielinksd-1 -c ${here}/../conf/${config}-1.toml) > /tmp/indielinksd-0/stdout.log 2>&1 < /dev/null &
(RUST_BACKTRACE=1 RUST_LOG="${rust_log}" cargo run --bin indielinksd -- -D -p -L /tmp/indielinksd-2 -c ${here}/../conf/${config}-2.toml) > /tmp/indielinksd-0/stdout.log 2>&1 < /dev/null &
if [ "${nodes}" == "5" ]; then
    (RUST_BACKTRACE=1 RUST_LOG="${rust_log}" cargo run --bin indielinksd -- -D -p -L /tmp/indielinksd-3 -c ${here}/../conf/${config}-3.toml) > /tmp/indielinksd-0/stdout.log 2>&1 < /dev/null &
    (RUST_BACKTRACE=1 RUST_LOG="${rust_log}" cargo run --bin indielinksd -- -D -p -L /tmp/indielinksd-4 -c ${here}/../conf/${config}-4.toml) > /tmp/indielinksd-0/stdout.log 2>&1 < /dev/null &
fi

# The problem with running these in subshells is that we arrive here with the
# build process (potentially) in-progress, which can take quite some time.

# Wait for the entire cluster to healthcheck
hc 20679 || exit 1
hc 20682 || exit 1
hc 20685 || exit 1
if [ "${nodes}" == "5" ]; then
    hc 20688 || exit 1
    hc 20691 || exit 1
fi

# If I don't place my `haproxy` invocation into a sub-shell, `Command::output()` hangs.
(haproxy -f ${here}/../indielinks-test/haproxy-${nodes}-nodes.conf) > /tmp/haproxy.log 2>&1 < /dev/null &
sleep 0.5

echo "indielinksd up & fronted by haproxy."
