#!/usr/bin/env bash
VERSION=0.0.1

set -euo pipefail

config_base=
help=
local_state_base="/tmp/indielinksd-cluster-"
nargs=0
node_id=
num_polls=120 # generous limit of two minutes
prev_option=
verbose=
version=
for option
do
    # If the previous option required an argument, assign it now.
    if test -n "$prev_option"; then
        eval $prev_option=\$option
        prev_option=
        nargs=$(($nargs+1))
        continue
    fi

    # Parse out the argument option in $option, if present.
    case $option in
        *=?*) optarg=$(expr "X$option" : '[^=]*=\(.*\)') ;;
        *=)   optarg= ;;
        *)    optarg=yes ;;
    esac

    # Options are handled here:
    case $option in
        -C | --config | --config-base)
            nargs=$(($nargs+1));
            prev_option=config_base;;
        -C=* | --config=* | --config-base=*)
            nargs=$(($nargs+1));
            config_base=$optarg;;
        -L | --local-state | --local-state-base)
            nargs=$(($nargs+1));
            prev_option=local_state_base;;
        -L=* | --local-state=* | --local-state-base=*)
            nargs=$(($nargs+1));
            local_state_base=$optarg;;
        -N | --num-polls | --num-checks)
            nargs=$(($nargs+1));
            prev_option=num_polls;;
        -N=* | --num-polls=* | --num-checks=*)
            nargs=$(($nargs+1));
            num_polls=$optarg;;
        -h | --he | --hel | --help)
            nargs=$(($nargs+1));
            help=yes;;
        -v | --verb | --verbose)
            nargs=$(($nargs+1));
            verbose=yes;;
        -V | --vers | --version)
            nargs=$(($nargs+1));
            version=yes;;
        -*)
            cat >&2 <<EOF
Unrecognized option '$option'.
Try '$0 --help' for more information.
EOF
            exit 2;;
        *)
            shift $nargs;
            # $@ now contains the arguments, $# the number of arguments
            node_id="$1"
            shift
        break;;
    esac

done

if test -n "${help}"; then
    cat <<EOF
indielinks-cluster-node-up -- Bring-up a single indielinks node in a cluster

Usage:

    indielinks-cluster-node-up [OPTION...] ID

Options:

    -h, --help      Print this message & exit
    -V, --version   Print this script's version & exit
    -v, --verbose   Produce prolix output
    -C CFG, --config-base=CFG  Specify the prefix to be used for
                    the indielinksd configuration files to be
                    used. Each instance will append its instance
                    number and ".toml" to this base, so
                    -C file- will produce configuration files of
                    file-0.toml, file-1.toml & so on.
    -L DIR, --local-state-base=DIR  Specify the directories where
                    indielinksd should place their pid file. Each
                    instance will append its instance number to this
                    prefix to get the final directory name, so
                    -L /tmp/x will produce directories /tmp/x{0,1,2}
                    for a three-node cluster.
                    Default "/tmp/indielinksd-"
    -N NUM, --num-polls=N  Specify the number of one second
                    interval polls of the indielinks /healthcheck
                    endpoint before determining the build didn't
                    come up. Default: 120 (it's long to account
                    for the possiblity of building the binary)

Argument:

This script takes a single argument: an integer in 0...4 (inclusive) identifying the node
to bring-up.
EOF
    exit 0
fi

if test -n "${version}"; then
    cat <<EOF
indielinks-cluster-node-up $VERSION
EOF
    exit 0
fi

if test -n "${verbose}"; then
    set -x
fi

# Invoke as `hc port num_polls`
function hc() {
    local port=$1
    local num_polls=$2
    # curl can fail if the server isn't up, yet
    status=$(curl -s http://localhost:${port}/healthcheck || true)
    ntries=1
    while [ "${status}" != "GOOD" -a "${status}" != "READY" ]; do
        sleep 1.0
        status=$(curl -s http://localhost:${port}/healthcheck || true)
        ntries=$(($ntries+1))
        if [ ${ntries} -gt ${num_polls} ]; then
            echo "indielinks failed to come up on port ${port}" >&2
            return "1"
        fi
    done
    return "0"
}

# Parse the public port from an indielinks configuration file
function parse_public_port() {
    local config_file=$1
    local port=$(sed -nE 's/public-address[[:space:]]*=[[:space:]]*"[.0-9]+:([0-9]+)"/\1/p' $config_file)
    echo $port
}

if [ -z "${config_base}" ]; then
    echo "--config-base is mandatory" >&2
    exit 2
fi

if [ $# -ne 0 ]; then
    echo "Unexpected argument(s); try 'indielinks-cluster-up --help'" >&2
    exit 2
fi

here=$(dirname $(realpath $0))
cd $here/../indielinks

# Parse the public ports on which our instances are listening from the given
# config files: public-address = "0.0.0.0:20679"
port=$(parse_public_port "${config_base}${node_id}.toml")

rust_log="${RUST_LOG:-debug,aws_config=warn,aws_runtime=info,aws_sdk_sts=info,aws_sigv4=info,aws_smithy_runtime=info,aws_smithy_runtime_api=info,aws_smithy_http_client=info,aws_sdk_dynamodb=info,hyper=info,scylla=info,openraft=info,h2::codec=info,h2::proto=info,hyper_util=info,tower::buffer=info}"

# (Re-)create the local state directories for each instance
test -d ${local_state_base}${node_id} || mkdir ${local_state_base}${node_id}

# Run three or five copies of the `indielinksd` daemon. If I don't place each
# `cargo run` invocation into a sub-shell, `Command::output()` hangs (?)
(RUST_BACKTRACE=1 RUST_LOG="${rust_log}" cargo run --bin indielinksd -- -D -p -L ${local_state_base}${node_id} -c ${config_base}${node_id}.toml) > ${local_state_base}${node_id}/stdout.log 2>&1 < /dev/null &

# The problem with running these in subshells is that we arrive here with the
# build process (potentially) in-progress, which can take quite some time. Wait
# for the entire cluster to healthcheck.
hc ${port} ${num_polls} || exit 1

echo "indielinksd node ${node_id} up."
