#!/usr/bin/env bash
if [ $# -ne 1 ]; then
    echo "Invoke as 'indielinks-up CONFIG-FILE'" >&2
    exit 2
fi
config="$1"
rust_log="debug,aws_config=warn,aws_runtime=info,aws_sdk_sts=info,aws_sigv4=info,aws_smithy_runtime=info,aws_smithy_runtime_api=info,aws_smithy_http_client=info,aws_sdk_dynamodb=info,hyper=info,scylla=info,openraft=info"

set -ex
here=$(dirname $(realpath $0))
cd $here/../indielinks
# Run `indielinks` as a daemon in the indielinks directory
RUST_BACKTRACE=1 RUST_LOG="${rust_log}" cargo run --bin indielinksd -- -D -p -C -c ${here}/../conf/${config}

sleep=0.5
# curl can fail if the server isn't up, yet
set +e
status=$(curl -s http://localhost:20679/healthcheck)
ntries=1
while [ "${status}" != "GOOD" ]; do
    sleep 0.5
    status=$(curl -s http://localhost:20679/healthcheck)
    ntries=$(($ntries+1))
    # Give it five seconds
    if [ ${ntries} -gt 10 ]; then
        echo "indielinksd failed to come up!" >&2
        exit 1
    fi
done

# Initialize this instance as a single-node Raft cluster
curl -v -H 'Content-Type: application/json' http://localhost:20680/ops/cache/init-cluster --data '{"0":{"addr":"127.0.0.1:20681"}}'
