#!/usr/bin/env bash
set -ex
here=$(dirname $(realpath $0))
cd $here
docker compose -f compose.local.yaml up -d
ntries=1
nnodes=$(docker exec scylla-node-1 nodetool status|grep -F UN|wc -l)
while [ ${nnodes} -ne 3 ]; do
    sleep 0.5
    set +e
    docker exec scylla-node-1 nodetool status
    set -e
    nnodes=$(docker exec scylla-node-1 nodetool status|grep -F UN|wc -l)
    ntries=$(($ntries+1))
    # Give it ten seconds
    if [ ${ntries} -gt 25 ]; then
        echo "ScyllaDB failed to come up" >&2
        exit 1
    fi
done
# docker cp indielinks.cql scylla-node-1:/indielinks.cql
# TODO(sp1ff): 
# docker cp dev-charge.cql scylla-node-1:/dev-charge.cql

# TODO(sp1ff): 
# docker exec -i scylla-node-1 cqlsh -e "create keyspace if not exists indielinks with replication = {'class': 'NetworkTopologyStrategy', 'replication_factor' : 3} and tablets = {'enabled': false};"
# docker exec -i scylla-node-1 cqlsh -f /indielinks.cql
# TODO(sp1ff): 
# docker exec -i scylla-node-1 cqlsh -f /dev-charge.cql
# RUST_LOG="debug,scylla::transport=debug" cargo run --bin indielinks-ddb -- \
#         -p -D http://localhost:8043

rust_log=debug,\
aws_config=info,\
aws_runtime=info,\
aws_sdk_dynamodb=info,\
aws_sdk_sts=info,\
aws_sigv4=info,\
aws_smithy_runtime=info,\
aws_smithy_runtime_api=info,\
hyper=info,\
openraft=info,\
scylla=info

RUST_LOG=${rust_log} cargo run --bin indielinks-schemas -- -D -p ddb http://localhost:8043
RUST_LOG=${rust_log} cargo run --bin indielinks-schemas -- -D -p scylla 127.0.0.1:9043
