#!/usr/bin/env bash
VERSION=0.0.1

set -euo pipefail

function hc {
    local bin="$1"
    local port="$2"
    local num_polls="$3"
    local status=$(curl -s http://localhost:${port}/healthcheck || true)
    local ntries=1
    while [ "${status}" != "GOOD" ]; do
        sleep 1.0
        status=$(curl -s http://localhost:${port}/healthcheck || true)
        ntries=$(($ntries+1))
        if [ ${ntries} -gt ${num_polls} ]; then
            echo "${bin}:${port} failed to come up; log file follows on stdout:" >&2
            ls -l "$log" || true
            cat "$log"
            echo "=== end stdout =="
            echo "ps & netstat output:"
            ps aux|grep -F "$bin"|grep -v grep
            sudo netstat -lpent|grep -F "$port"|grep -v grep
            return "1"
        fi
    done
    return "0"
}

help=
nargs=0
num_polls=120 # generous limit of two minutes
prev_option=
verbose=
version=
for option
do
    # If the previous option required an argument, assign it now.
    if test -n "$prev_option"; then
        eval $prev_option=\$option
        prev_option=
        nargs=$(($nargs+1))
        continue
    fi

    # Parse out the argument option in $option, if present.
    case $option in
        *=*) optarg=${option#*=} ;;
        *)   optarg=yes ;;
    esac

    # Options are handled here:
    case $option in
        -N | --num-polls | --num-checks)
            nargs=$(($nargs+1));
            prev_option=num_polls;;
        -N=* | --num-polls=* | --num-checks=*)
            nargs=$(($nargs+1));
            num_polls=$optarg;;
        -h | --he | --hel | --help)
            nargs=$(($nargs+1));
            help=yes;;
        -v | --verb | --verbose)
            nargs=$(($nargs+1));
            verbose=yes;;
        -V | --vers | --version)
            nargs=$(($nargs+1));
            version=yes;;
        -*)
            cat >&2 <<EOF
Unrecognized option '$option'.
Try 'single-node-cluster-up --help' for more information.
EOF
            exit 2;;
        *)
            break;;
    esac

done

shift $nargs;
# $@ now contains the arguments, $# the number of arguments

if test -n "${help}"; then
    cat <<EOF
single-node-cluster-up -- Stand-up a single node indielinks cache cluster

Usage:

    single-node-cluster-up [OPTION...] BIN PORT

Options:

    -h, --help      Print this message & exit
    -V, --version   Print this script's version & exit
    -v, --verbose   Produce prolix output
    -N NUM, --num-polls=NUM  Specify the number of half-second
                    interval polls of the /healthcheck endpoint
                    before determining the node didn't come up.
                    Default: 20

Arguments:

    BIN             Cache test binary to run; expected to be
                    "in-memory" or "on-disk".
    PORT            Localhost port on which the single node should
                    listen.

EOF
    exit 0
fi

if test -n "${version}"; then
    cat <<EOF
single-node-cluster-up $VERSION
EOF
    exit 0
fi

if test -n "${verbose}"; then
    set -x
fi

if [ $# -ne 2 ]; then
    echo "Invoke as 'single-node-cluster-up BIN PORT'" >&2
    echo "Try 'single-node-cluster-up --help'" >&2
    exit 2
fi
bin="$1"
port="$2"

here=$(dirname $(realpath $0))
cd $here/../tests-indielinks-cache

if [ "${bin}" == "on-disk" ]; then
    mkdir /tmp/on-disk-node-0
fi

# Stand-up a single-node cluster. If I don't place each `cargo run` invocation
# into a sub-shell, `Command::output()` hangs.
(RUST_BACKTRACE=1 RUST_LOG=debug cargo run --bin "${bin}" -- -c 0 127.0.0.1:${port}) > n0.log 2>&1 < /dev/null &

# Now healthcheck each instance
hc "${bin}" ${port} ${num_polls}

exit 0
