#!/usr/bin/env bash

set -euo pipefail

function hc {
    local bin="$1"
    local port="$2"
    local status=$(curl -s http://localhost:${port}/healthcheck || true)
    local ntries=1
    while [ "${status}" != "GOOD" ]; do
        sleep 0.5
        ntries=$(($ntries+1))
        # Give it ten seconds
        if [ ${ntries} -gt 20 ]; then
            echo "${bin} failed to come up" >&2
            set -e
            return "1"
        fi
        status=$(curl -s http://localhost:${port}/healthcheck || true)
    done
    return "0"
}

if [ $# -ne 2 ]; then
    echo "Invoke as 'single-node-cluster-up [in-memory|on-disk] PORT'" >&2
    exit 2
fi
bin="$1"
port="$2"

set -x
here=$(dirname $(realpath $0))
cd $here/../tests-indielinks-cache

if [ "${bin}" == "on-disk" ]; then
    mkdir /tmp/on-disk-node-0
fi

# Stand-up a single-node cluster. If I don't place each `cargo run` invocation
# into a sub-shell, `Command::output()` hangs.
(RUST_BACKTRACE=1 RUST_LOG=debug cargo run --bin "${bin}" -- -c 0 127.0.0.1:${port}) > n0.log 2>&1 < /dev/null &

# Now healthcheck each instance
hc "${bin}" ${port}

exit 0
