#!/usr/bin/env bash
VERSION=0.0.1

set -euo pipefail

help=
nargs=0
prev_option=
public_port=20679
stack_name=
verbose=
version=
for option
do
    # If the previous option required an argument, assign it now.
    if test -n "$prev_option"; then
        eval $prev_option=\$option
        prev_option=
        nargs=$(($nargs+1))
        continue
    fi

    # Parse out the argument option in $option, if present.
    case $option in
        *=?*) optarg=$(expr "X$option" : '[^=]*=\(.*\)') ;;
        *=)   optarg= ;;
        *)    optarg=yes ;;
    esac

    # Options are handled here:
    case $option in
        -h | --he | --hel | --help)
	        nargs=$(($nargs+1));
            help=yes;;
        -p | --public-port)
	        nargs=$(($nargs+1));
            prev_option=public_port;;
        -p=* | --public-port=*)
	        nargs=$(($nargs+1));
            public_port=$optarg;;
        -s | --stack | --stack-name)
	        nargs=$(($nargs+1));
            prev_option=stack_name;;
        -s=* | --stack=* | --stack-name=*)
	        nargs=$(($nargs+1));
            stack_name=$optarg;;
        -v | --verb | --verbose)
	        nargs=$(($nargs+1));
            verbose=yes;;
        -V | --vers | --version)
	        nargs=$(($nargs+1));
            version=yes;;
        -*)
            cat >&2 <<EOF
Unrecognized option '$option'.
Try 'stunnel-up --help' for more information.
EOF
            exit 2;;
	    *)
	        # $@ now contains the arguments, $# the number of arguments
	        shift $nargs;
	        break;;
    esac

done

if test -n "${help}"; then
    cat <<EOF
stunell-up -- stand-up an stunnel instance terminating TLS for indielinks

Usage:

    stunnel-up [OPTION...] ARGUMENT...

Options:

    -h, --help      Print this message & exit
    -V, --version   Print this script's version & exit
    -v, --verbose   Produce prolix output
    -p PORT, --public-port=PORT   Public API port for the indielinks instance
                    for which TLS is being terminated [default: 20679]
    -s NAME, --stack-name=NAME    Integration testing "stack" identifier
                    [default: none]

NB This script (and its twin, 'stunnel-down') assumes that there is no other
'stunnel' running on the host. It also binds port 443, so the caller must
have sudo privileges, and not be running another process on that port.
EOF
    exit 0
fi

if test -n "${version}"; then
    cat <<EOF
stunnel-up $VERSION
EOF
    exit 0
fi

if test -n "${verbose}"; then
    set -x
fi

shift $nargs
if test $# -gt 0; then
    cat >&2 <<EOF
Unrecognized argument(s).
Try 'stunnel --help' for more information.
EOF
fi

here=$(dirname $(realpath $0))
cd $here

suffix=
if test -n "${stack_name}"; then
    suffix="-${stack_name}"
fi

# Emit an stunnel configuration file
stunnel_config=/tmp/stunnel${suffix}.conf
cat > ${stunnel_config} <<EOF
debug = 5
foreground = no
output = /tmp/stunnel${suffix}.log
cert = indiemark.local.pem
key = indiemark.local-key.pem
client = no
[https]
accept  = 443
connect = 127.0.0.1:${public_port}
EOF

sudo stunnel ${stunnel_config}

ntries=1
status=$(sudo netstat -lpent|grep '0.0.0.0:443'|grep stunnel|grep -v grep)
while [ -z "$status" ]; do
    ntries=$(($ntries+1))
    # Give it ten seconds
    if [ ${ntries} -gt 25 ]; then
        echo "stunnel failed to come up" >&2
        exit 1
    fi
    sleep 0.5
    status=$(sudo netstat -lpent|grep '0.0.0.0:443'|grep stunnel|grep -v grep)
done
