[package]
name = "tests-indielinks-cache"
version = "0.0.1"
edition = "2024"

[dependencies]
async-trait = { workspace = true }
axum = { workspace = true, features = ["macros"] }
bpaf = { workspace = true, features = ["bright-color"] }
http = { workspace = true }
indielinks-cache = { workspace = true }
indielinks-shared = { workspace = true }
libtest-mimic = { workspace = true }
openraft = { workspace = true, features = ["serde", "storage-v2"] }
reqwest = { workspace = true, features = ["blocking", "json"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
snafu = { workspace = true, features = ["backtrace"] }
tap = { workspace = true }
test-log = { workspace = true, features = ["trace"] }
tokio = { workspace = true, features = ["rt-multi-thread", "signal"] }
tower-http = { workspace = true, features = ["trace"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["ansi", "env-filter"] }

[build-dependencies]
nickel-lang = { workspace = true }

[dev-dependencies]
inventory = { workspace = true }
tests-support = { workspace = true }

[[test]]
name = "cache-cluster-tests"
harness = false
