[package]
name = "indielinks-fe"
version = "0.0.1"
edition = "2024"

[dependencies]
chrono = { workspace = true, features = ["serde"] }
console_error_panic_hook = { workspace = true }
futures = { workspace = true }
gloo-net = { workspace = true, features = ["http"] }
indielinks-shared = { workspace = true }
itertools = { workspace = true }
leptos = { workspace = true, features = ["csr"] }
leptos_router = { workspace = true }
nonempty-collections = { workspace = true, features = ["serde"] }
serde = { workspace = true, features = ["derive"] }
serde_urlencoded = { workspace = true }
serde-wasm-bindgen = { workspace = true }
snafu = { workspace = true }
tap = { workspace = true }
thaw = { workspace = true, features = ["csr"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tracing-subscriber-wasm = { workspace = true }
url = { workspace = true, features = ["serde"] }
uuid = { workspace = true, features = ["v4", "serde"] }
wasm-bindgen = { workspace = true }
wasm-cookies = { workspace = true }
web-sys = { workspace = true }
reactive_stores = { workspace = true }
send_wrapper = { workspace = true }
secrecy = { workspace = true, features = ["serde"] }
gloo-timers = { workspace = true, features = ["futures"] }
icondata = { workspace = true }
nonzero = { workspace = true }
