#!/usr/bin/env bash
VERSION=0.0.1

set -euo pipefail

help=
nargs=0
prev_option=
verbose=
version=
for option
do
    # If the previous option required an argument, assign it now.
    if test -n "$prev_option"; then
        eval $prev_option=\$option
        prev_option=
        nargs=$(($nargs+1))
        continue
    fi

    # Parse out the argument option in $option, if present.
    case $option in
        *=?*) optarg=$(expr "X$option" : '[^=]*=\(.*\)') ;;
        *=)   optarg= ;;
        *)    optarg=yes ;;
    esac

    # Options are handled here:
    case $option in
        -h | --he | --hel | --help)
	        nargs=$(($nargs+1));
            help=yes;;
        -v | --verb | --verbose)
	        nargs=$(($nargs+1));
            verbose=yes;;
        -V | --vers | --version)
	        nargs=$(($nargs+1));
            version=yes;;
        -*)
            cat >&2 <<EOF
Unrecognized option '$option'.
Try 'build-debian-packages --help' for more information.
EOF
            exit 2;;
	    *)
	        # $@ now contains the arguments, $# the number of arguments
	        shift $nargs;
	        break;;
    esac

done

if test -n "${help}"; then
    cat <<EOF
'build-debian-packages' -- build all indielinks Debian binary packages

Usage:

    build-debian-packages [OPTION...] ARGUMENT...

Options:

    -h, --help      Print this message & exit
    -V, --version   Print this script's version & exit
    -v, --verbose   Produce prolix output

Discussion:

This should almost certainly, outside of development testing, be run in a
Docker container based on a Debian image. This is because the Debian
repositories, famously slow to update, likely contain a copy of glibc several
versions behind that on your development machine (unless, I suppose, you're
developing on Debian). Since we're building binary packages, attempting to
install the resulting packages on a Debian host would produce glibc errors. See
'debian/README.org' for more details.
EOF
    exit 0
fi

if test -n "${version}"; then
    cat <<EOF
build-debian-packages $VERSION
EOF
    exit 0
fi

if test -n "${verbose}"; then
    set -x
fi


here=$(dirname "$(realpath "$0")")
cd "$here/.."

# Assumes we're in the distribution driectory
function finalize_assets () {
    wasm=$(ls -1 indielinks-fe*.wasm)
    js=$(ls -1 indielinks-fe*.js)
    css=$(ls -1 tailwind-*.css)
    mv "$wasm" indielinks-fe.wasm
    mv "$js" indielinks-fe.js
    mv "$css" style.css
    sed -i -e "s@${wasm}@indielinks-fe.wasm@g" index.html
    sed -i -e "s@${js}@indielinks-fe.js@g" index.html
    sed -i -e "s@${css}@style.css@g" index.html
}

function build_local_assets () {
    local old_pwd="$PWD"
    rm -rf dist
    INDIELINKS_FE_API="http://localhost:20676" \
        INDIELINKS_BASE="" \
        INDIELINKS_PAGE_SIZE="20" \
        trunk build --release
    cd dist
    finalize_assets
    cd "$old_pwd"
}

function build_aws_assets () {
    local old_pwd="$PWD"
    rm -rf dist-aws
    INDIELINKS_FE_API="https://indiemark.sh" \
        INDIELINKS_BASE="" \
        INDIELINKS_PAGE_SIZE="20" \
        trunk build --release --dist dist-aws
    cd dist-aws
    finalize_assets
    cd "$old_pwd"
}

function build_packages () {
    local release="$1"
    local old_pwd="$PWD"
    cd indielinks
    cargo deb --no-build --deb-version=${release}
    cargo deb --no-build --variant=aws --deb-version=${release}
    cd "$old_pwd"
}

# Pick-up the version from the environment (if we're in a container), or from
# the command line (the latter won't work from inside a container, since it
# won't see the full repo, just the current worktree).
revision="r${GIT_COMMIT:-$(git rev-parse --short HEAD)}"
version=$(cargo pkgid -p indielinks | sed 's/.*#//')
release="${version}~git.${revision}"

cargo build --release

cd indielinks-fe
tailwindcss -i style.css -o tailwind.css
build_local_assets
build_aws_assets
cd ..

admin/validate-aws-frontend indielinks-fe/dist-aws

build_packages $release
