#!/usr/bin/env bash

# This script will bind mount the project directory into a Debian
# container, build a Debian package, test it in the container,
# and leave the package in `target/debian`.
set -ex

here=$(dirname $(realpath $0))
project=${here}/..
script=${here}/build-and-test-debian-package-in-container
cd ${here}
docker build -t indielinks-debian:latest \
       -f Dockerfile-debian-packaging \
       --label "indielinks-debian" \
       --build-arg UID="$(id -u)" \
       --build-arg GID="$(id -g)" \
       .

docker compose -f compose.debian-packaging.yaml up -d
echo "Waiting on 'host'..."
docker compose -f compose.debian-packaging.yaml wait host
status=$?
echo "Waiting on 'host'...done($status)."
docker logs debian-packaging-host-1
docker compose -f compose.debian-packaging.yaml down
