#!/usr/bin/env bash

# This script is presumably mounted in a Debian container. It will
# use `cargo deb` to build the Debian package & minimally test it.
set -ex
source $HOME/.cargo/env
cd /indielinks
ver=$(printf "r%s" "$(git rev-list --count HEAD)")
rel="0.0.1~git.${ver}"
cargo deb --manifest-path=indielinks/Cargo.toml --deb-version=${rel}
pkg=$(ls -1 target/debian/indielinks*.deb|head -n1)
sudo dpkg --debug=2 -i ${pkg}
indielinksd --version
indielinks-schemas --version
indic --help
scylla=$(dig +short scylla-node-1)
sudo sed -i -e "s@^hosts = \\[\".*@hosts = [\"${scylla}:9042\"]@" /etc/indielinks.toml
indielinks-post-install -s ${scylla}:9042
# indielinks now up & running
indic -A http://127.0.0.1:20676 add-user -u john.doe -p 'f00-b@r-sp1at' -m 'john.doe@gmail.com'
sudo dpkg --debug=2 -r indielinks

