#!/usr/bin/env bash
INDIELINKS_CACHE_TESTS_CONFIG=conf/cache-tests-front-end.toml \
INDIELINKS_SMOKE_TESTS_CONFIG=conf/smoke-tests-front-end.toml \
INDIELINKS_BACKGROUND_TASK_TESTS_CONFIG=conf/background-task-tests-front-end.toml \
time limitcpu /home/mgh/.cargo/bin/cargo -f -l 800 -- test
