# Docker compose file enabling indielinks testing as part of Debian packaging

name: debian-packaging

services:

  scylla-node-1:
    container_name: deb-scylla-node-1
    image: scylladb/scylla:latest
    command: --smp 1 --alternator-port 8042 --alternator-write-isolation only_rmw_uses_lwt # always_use_lwt?

  scylla-node-2:
    container_name: deb-scylla-node-2
    image: scylladb/scylla:latest
    command: --smp 1 --seeds=scylla-node-1  --alternator-port 8042 --alternator-write-isolation only_rmw_uses_lwt
    depends_on:
      - scylla-node-1

  scylla-node-3:
    container_name: deb-scylla-node-3
    image: scylladb/scylla:latest
    command: --smp 1 --seeds=scylla-node-1 --alternator-port 8042 --alternator-write-isolation only_rmw_uses_lwt
    depends_on:
      - scylla-node-1

  host:
    image: indielinks-debian:latest
    # Use this to leave the container running, presumably so one can get a shell within
    # command: tail -f /dev/null
    command: /build-and-exercise-package
    depends_on:
      - scylla-node-1
    volumes:
      - ./build-and-test-debian-package-in-container:/build-and-exercise-package:ro
      - ..:/indielinks
