#!/usr/bin/env bash

# This is a start on an installation procedure. I hope to eventually produce
# Arch and Debian packages, as well as an OpenTofu script, but for now I just
# want to begin running indielinks locally on my desktop. Even when I move to
# Arch or Debian packaging, the packaging step will need some scripting to
# build & configure the installation, anyway.

###########################################################################
#                                     main                                #
###########################################################################

help=
nargs=0
prev_option=
verbose=
version=
for option
do
    # If the previous option required an argument, assign it now.
    if test -n "$prev_option"; then
        eval $prev_option=\$option
        prev_option=
        nargs=$(($nargs+1))
        continue
    fi

    # Parse out the argument option in $option, if present.
    case $option in
        *=?*) optarg=$(expr "X$option" : '[^=]*=\(.*\)') ;;
        *=)   optarg= ;;
        *)    optarg=yes ;;
    esac

    # Options are handled here:
    case $option in
        -h | --he | --hel | --help)
	        nargs=$(($nargs+1));
            help=yes;;
        -v | --verb | --verbose)
	        nargs=$(($nargs+1));
            verbose=yes;;
        -V | --vers | --version)
	        nargs=$(($nargs+1));
            version=yes;;
        -*)
            cat >&2 <<EOF
Unrecognized option '$option'.
Try 'local-install --help' for more information.
EOF
            exit 2;;
	    *)
	        # $@ now contains the arguments, $# the number of arguments
	        shift $nargs;
	        break;;
    esac

done

if test -n "${help}"; then
    cat <<EOF
local-install -- First indielinks installation script

Usage:

    $0 [OPTION...] ARGUMENT...

Options:

    -h, --help      Print this message & exit
    -V, --version   Print this script's version & exit
    -v, --verbose   Produce prolix output

EOF
    exit 0
fi

if test -n "${version}"; then
    cat <<EOF
local-install 0.0.1
EOF
    exit 0
fi

if test -n "${verbose}"; then
    set -x
fi

set -e

nproc=$(nproc)
nproc=$(($nproc/4))
if [ $nproc -eq 0 ]; then
    nproc=1
fi

here=$(dirname $(realpath $0))
cd $here/..
cargo build --release -j ${nproc}
cd indielinks-fe
INDIELINKS_FE_API="http://localhost:20676" INDIELINKS_BASE="/fe" INDIELINKS_PAGE_SIZE="20" trunk build --release
cd ..

install -C -D -t /home/$USER/bin target/release/indielinksd
install -C -D -t /home/$USER/bin target/release/indic
install -C -D -t /home/$USER/bin target/release/indielinks-schemas
install -C -D -t /home/$USER/bin scripts/indielinks-post-install
install -C -D -t /home/$USER/bin scripts/indielinks-ctl

cd indielinks-fe/dist
wasm=$(ls -1 indielinks-fe*.wasm)
js=$(ls -1 indielinks-fe*.js)
css=$(ls -1 style-*.css)
mv -v $wasm indielinks-fe.wasm
mv -v $js indielinks-fe.js
mv -v $css style.css
sed -i -e s@$wasm@fe/indielinks-fe.wasm@g index.html
sed -i -e s@$js@fe/indielinks-fe.js@g index.html
sed -i -e s@$css@fe/style.css@g index.html

install -C -D index.html         /home/$USER/share/indielinks/assets/index.html
install -C -D indielinks-fe.js   /home/$USER/share/indielinks/assets/indielinks-fe.js
install -C -D style.css          /home/$USER/share/indielinks/assets/style.css
install -C -D indielinks-fe.wasm /home/$USER/share/indielinks/assets/indielinks-fe.wasm
cd ../..

install -D indielinks/local-indielinks.toml /home/$USER/etc/indielinks.toml
sed -i -e s@/home/USER/@/home/$USER/@ /home/$USER/etc/indielinks.toml

mkdir -p $HOME/var/{log,run}

echo "indielinks has been installed under your home directory."
echo "Now run indielinks-post-install to configure ScyllaDB & start the service."
