#!/bin/bash
set -euxo pipefail

if rg -t rust -t protobuf -t css -t html -g '!.personal' 'TODO|TOOD|LATER|IN-?PROGRESS|\\todo|todo!|dbg!'; then
    echo "You have TODO-s"
    exit 1
fi

if rg -t rust -g '!.personal' -F 'rmp_serde::to_vec('; then
    echo "You used rmp_serde::to_vec(); prefer to_vec_named()."
    exit 1
fi

nproc=$(nproc)
nproc=$(($nproc/4))
if [ $nproc -eq 0 ]; then
    nproc=1
fi

set -e
cargo clippy -j ${nproc} -- --no-deps -Dwarnings
cargo fmt -- --check
RUSTDOCFLAGS=-Dwarnings cargo doc --no-deps -j ${nproc}
# Need to address these two, plus a host of warnings
# Actually, just turning the thing off, for now.
# cargo audit --ignore=RUSTSEC-2023-0071 --ignore=RUSTSEC-2026-0001 --ignore=RUSTSEC-2026-0049 --ignore=RUSTSEC-2026-0098 --ignore=RUSTSEC-2026-0099

