#!/bin/bash
set -x

if rg -t rust -t protobuf -g '!.old-files' -g '!hello-scylla' 'TODO|TOOD|LATER|IN-?PROGRESS|\\todo|todo!|dbg!'; then
    echo "You have TODO-s"
    exit 1
fi

nproc=$(nproc)
nproc=$(($nproc/4))
if [ $nproc -eq 0 ]; then
    nproc=1
fi

set -e
cargo clippy -j ${nproc} -- --no-deps -Dwarnings \
      -A clippy::result_large_err \
      -A clippy::uninlined_format_args
cargo fmt -- --check
RUSTDOCFLAGS=-Dwarnings cargo doc --no-deps -j ${nproc}
# Need to address these two, plus a host of warnings
cargo audit --ignore=RUSTSEC-2023-0071 --ignore=RUSTSEC-2026-0001

