[package]
name = "indielinks-shared"
version = "0.0.1"
edition = "2024"

[dependencies]
async-trait = { workspace = true }
atom_syndication = { workspace = true }
bytes = { workspace = true } # RUSTSEC-2026-0007
chrono = { workspace = true, features = ["serde"] }
either = { workspace = true }
email_address = { workspace = true }
# `getrandom` is really a transitive dependency, but we need the "js"
# feature for indielinks-fe builds (indielinks-fe depends on this
# crate). This is required despite what `cargo outdated` may say.
getrandom = { workspace = true, features = ["js"] }
hex = { workspace = true }
http = { workspace = true }
lazy_static = { workspace = true }
lz4_flex = { workspace = true } # RUSTSEC-2026-0041
nonempty-collections = { workspace = true, features = ["serde"] }
opentelemetry = { workspace = true }
picky = { workspace = true }
pin-project = { workspace = true }
pkcs8 = { workspace = true }
rand = { workspace = true }
regex = { workspace = true }
reqwest = { workspace = true }
rmp-serde = { workspace = true }
rsa = { workspace = true }
scylla = { workspace = true, features = ["full-serialization"], optional = true }
secrecy = { workspace = true, features = ["serde"] }
serde = { workspace = true, features = ["derive"] }
snafu = { workspace = true, features = ["backtrace"] }
tap = { workspace = true }
time = { workspace = true } # RUSTSEC-2026-0009
tower = { workspace = true, features = ["retry"] }
typenum = { workspace = true }
unicode-segmentation = { workspace = true }
url = { workspace = true, features = ["serde"] }
uuid = { workspace = true, features = ["serde", "v4"] }

[dev-dependencies]
tokio = { workspace = true, features = ["rt", "macros"] }

[features]
default = []

__internal = []
backend = ["scylla", "__internal"]
