[package]
name = "tests-indielinks"
version = "0.0.1"
edition = "2021"

[dependencies]
approx = { workspace = true }
async-trait = { workspace = true }
aws-config = { workspace = true, features = ["behavior-version-latest"] }
aws-sdk-dynamodb = { workspace = true }
aws-smithy-runtime-api = { workspace = true, features = ["client"] }
axum = { workspace = true }
base64 = { workspace = true }
chrono = { workspace = true }
crypto-common = { workspace = true }
either = { workspace = true, features = ["serde"] }
futures = { workspace = true }
governor = { workspace = true }
hex = { workspace = true }
http = { workspace = true }
indielinks = { workspace = true }
indielinks-cache = { workspace = true }
indielinks-shared = { workspace = true, features = ["backend"] }
inventory = { workspace = true }
itertools = { workspace = true }
lazy_static = { workspace = true }
libc = { workspace = true }
libtest-mimic = { workspace = true }
lz4_flex = { workspace = true } # RUSTSEC-2026-0041
nonempty-collections = { workspace = true, features = ["serde"] }
nonzero = { workspace = true }
once_cell = { workspace = true }
openraft = { workspace = true, features = ["serde", "storage-v2"] }
picky = { workspace = true }
regex = { workspace = true }
reqwest = { workspace = true, features = ["blocking", "json"] }
rmp-serde = { workspace = true }
scylla = { workspace = true, features = ["chrono-04"] }
secrecy = { workspace = true }
serde = { workspace = true, features = ["serde_derive"] }
serde_dynamo = { workspace = true }
serde_json = { workspace = true }
serde_toml = { workspace = true }
sha2 = { workspace = true }
snafu = { workspace = true, features = ["backtrace"] }
tap = { workspace = true }
tests-support = { workspace = true }
tokio = { workspace = true, features = ["net", "rt", "rt-multi-thread", "time"] }
toml = { workspace = true }
tower-gcra = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
url = { workspace = true }
uuid = { workspace = true }
waitpid-any = { workspace = true }
wiremock = { workspace = true }

[build-dependencies]
nickel-lang = { workspace = true }

[[test]]
name = "background-task-tests"
harness = false

[[test]]
name = "cache-tests"
harness = false

[[test]]
name = "smoke-tests"
harness = false
