#!/usr/bin/env bash
VERSION=0.0.1

set -euo pipefail

help=
nargs=0
prev_option=
verbose=
version=
for option
do
    # If the previous option required an argument, assign it now.
    if test -n "$prev_option"; then
        eval $prev_option=\$option
        prev_option=
        nargs=$(($nargs+1))
        continue
    fi

    # Parse out the argument option in $option, if present.
    case $option in
        *=?*) optarg=$(expr "X$option" : '[^=]*=\(.*\)') ;;
        *=)   optarg= ;;
        *)    optarg=yes ;;
    esac

    # Options are handled here:
    case $option in
        -h | --he | --hel | --help)
	        nargs=$(($nargs+1));
            help=yes;;
        -v | --verb | --verbose)
	        nargs=$(($nargs+1));
            verbose=yes;;
        -V | --vers | --version)
	        nargs=$(($nargs+1));
            version=yes;;
        -*)
            cat >&2 <<EOF
Unrecognized option '$option'.
Try 'build-debian-image --help' for more information.
EOF
            exit 2;;
	    *)
	        # $@ now contains the arguments, $# the number of arguments
	        shift $nargs;
	        break;;
    esac

done

if test -n "${help}"; then
    cat <<EOF
'build-debian-image' -- build the 'indielinks-debian' Docker image

Usage:

    build-debian-image [OPTION...] ARGUMENT...

Options:

    -h, --help      Print this message & exit
    -V, --version   Print this script's version & exit
    -v, --verbose   Produce prolix output

EOF
    exit 0
fi

if test -n "${version}"; then
    cat <<EOF
'build-debian-image' $VERSION
EOF
    exit 0
fi

if test -n "${verbose}"; then
    set -x
fi

here=$(dirname $(realpath $0))
cd ${here}
# May want to make the tag and/or label configurable via command-line
# arguments, at some point.
exec docker build -t indielinks-debian:latest \
       -f Dockerfile                          \
       --label "indielinks-debian"            \
       --build-arg UID="$(id -u)"             \
       --build-arg GID="$(id -g)"             \
       .
