#!/usr/bin/env bash

# This script is presumably mounted in a Debian container. It will use `cargo
# deb` to build the Debian package, install it (as a free-standing SysV daemon)
# & minimally test it. For testing the Debian package with systemd, please see
# `test-debian-package-systemd`.
#
# For testing the Debian package used to deploy to AWS, please see
# `test-debian-aws-package`.
set -ex
source $HOME/.cargo/env
cd /indielinks

# Unhappy, but we need to build everything for Debian here (see the README)
cargo clean
admin/build-debian-packages

pkg=$(ls -1 target/debian/indielinks_*.deb|head -n1)
aws_pkg=$(ls -1 target/debian/indielinks-aws_*.deb|head -n1)

sudo dpkg --debug=2 -i ${pkg}
indielinksd --version
indielinks-schemas --version
indielinks-ctl --version
indic --help

# Test conflict: the AWS package must fail to install
if sudo dpkg -i "${aws_pkg}" 2>/dev/null; then
    echo "The AWS package installed despite the base package being present" >&2
    exit 1
fi

# simulate the operator hand-editing the indielinks config file
scylla=$(dig +short scylla-node-1)
sudo sed -i -e "s@^hosts = \\[\".*@hosts = [\"${scylla}:9042\"]@" /etc/indielinks.toml
indielinks-post-install --verbose -s ${scylla}:9042 --no-systemd
# Wait a few moments for the service to healthcheck
sleep 0.5
n=0
hc=$(curl -s http://127.0.0.1:20676/healthcheck)
if [ "${hc}" != "GOOD" ]; then
    sleep 0.5
    n=$(($n+1))
    if [ $n -gt 20 ]; then
        echo "indielinks failed to come up" >&2
        exit 1
    fi
    hc=$(curl -s http://127.0.0.1:20676/healthcheck)
fi
# indielinks now up & running
indic -A http://127.0.0.1:20676 -O http://127.0.0.1:20677 add-user -u john.doe -p 'f00-b@r-sp1at' -m 'john.doe@gmail.com'
# Check that the front-end is being served at the root
status_code=$(curl -s -o /dev/null -w '%{http_code}\n' http://127.0.0.1:20676/)
if [ ${status_code} -ne 200 ]; then
    echo "requesting the front-end returned status code ${status_code}" >&2
    exit 1
fi
indielinks-ctl -v restart
indielinks-ctl -v stop
sudo dpkg --debug=2 -r indielinks

