#!/usr/bin/env bash

function current_leader {
    local node_id=$1
    curl -s http://127.0.0.1:3080${node_id}/admin/metrics|jq .raft.current_leader
}

function kill_all {
    for pid in $(ps aux|grep debug/on-disk|grep -v grep|awk '{print $2}'); do
        echo "Killing PID $pid"
        kill $pid
    done
    for dir in ls -d /tmp/on-disk-node-*; do
        rm -rf ${dir}
    done
}

set -e
kill_all

mkdir /tmp/on-disk-node-0
mkdir /tmp/on-disk-node-1
mkdir /tmp/on-disk-node-2
mkdir /tmp/on-disk-node-3
mkdir /tmp/on-disk-node-4

cargo run --bin=on-disk -- 0 127.0.0.1:30800 2>&1 > n0.log &
sleep 1
cargo run --bin=on-disk -- 1 127.0.0.1:30801 2>&1 > n1.log &
sleep 1
cargo run --bin=on-disk -- 2 127.0.0.1:30802 2>&1 > n2.log &
sleep 1
cargo run --bin=on-disk -- 3 127.0.0.1:30803 2>&1 > n3.log &
sleep 1
cargo run --bin=on-disk -- 4 127.0.0.1:30804 2>&1 > n4.log &
sleep 1

echo -n "First metrics: "
curl -s http://127.0.0.1:30800/admin/metrics
echo

echo "Initializing a three-node cluster"
curl -s \
     -H 'Content-Type: application/json' \
     --data '[[0, "127.0.0.1:30800"], [1, "127.0.0.1:30801"], [2, "127.0.0.1:30802"]]' \
     http://127.0.0.1:30800/admin/init
sleep 1

echo -n "Current leader: "
current_leader 2
echo

echo -n "Cache 1: foo :=>"
curl -s -X GET -H 'Content-Type: application/json' http://127.0.0.1:30800/cache/lookup --data '{"cache":1,"key":"foo"}'|jq .
echo

echo -n "Insert foo :=> 11"
curl -s -H 'Content-Type: application/json' http://127.0.0.1:30800/cache/insert --data '{"cache":1,"key":"foo","value":11}'
echo

echo -n "Cache 1: foo :=>"
curl -s -X GET -H 'Content-Type: application/json' http://127.0.0.1:30800/cache/lookup --data '{"cache":1,"key":"foo"}'|jq .
echo

echo "Current hash ring: "
curl -s \
     -H 'Content-Type: application/json' \
     http://127.0.0.1:30800/app/hash-ring

echo
echo "Add nodes 3 & 4 as learners"
curl -s \
     -H 'Content-Type: application/json' \
     --data '[3, "127.0.0.1:30803"]' \
     http://127.0.0.1:30800/admin/add-learner
curl -s \
     -H 'Content-Type: application/json' \
     --data '[4, "127.0.0.1:30804"]' \
     http://127.0.0.1:30800/admin/add-learner

echo
echo "Adding nodes 3 & 4 to the cluster"

sleep 1

curl -s \
     -H 'Content-Type: application/json' \
     --data '[0, 1, 2, 3, 4]' \
     http://127.0.0.1:30800/admin/membership

echo
echo -n "Retrieve metrics from node 4:"
curl -s http://127.0.0.1:30804/admin/metrics|jq .

sleep 1

echo -n "Cache 1: foo :=>"
curl -s -X GET -H 'Content-Type: application/json' http://127.0.0.1:30804/cache/lookup --data '{"cache":1,"key":"foo"}'|jq .
echo

echo
echo "Killing all nodes..."
kill_all
echo "Killing all nodes...done."
