#!/usr/bin/env bash

# Trivial script to exercise `indielinks-cache` as a standalone Raft cluster

function current_leader {
    local node_id=$1
    curl -s http://127.0.0.1:2080${node_id}/admin/metrics|jq .current_leader
}

function kill_all {
    for pid in $(ps aux|grep debug/node|grep -v grep|awk '{print $2}'); do
        echo "Killing PID $pid"
        kill $pid
    done
}

set -e
kill_all

cargo run --bin=in-memory -- 0 127.0.0.1:20800 2>&1 > n0.log &
sleep 1
cargo run --bin=in-memory -- 1 127.0.0.1:20801 2>&1 > n1.log &
sleep 1
cargo run --bin=in-memory -- 2 127.0.0.1:20802 2>&1 > n2.log &
sleep 1
cargo run --bin=in-memory -- 3 127.0.0.1:20803 2>&1 > n3.log &
sleep 1
cargo run --bin=in-memory -- 4 127.0.0.1:20804 2>&1 > n4.log &
sleep 1

echo -n "First metrics: "
curl -s http://127.0.0.1:20800/admin/metrics
echo

echo "Initializing a three-node cluster"
curl -s \
     -H 'Content-Type: application/json' \
     --data '[[0, "127.0.0.1:20800"], [1, "127.0.0.1:20801"], [2, "127.0.0.1:20802"]]' \
     http://127.0.0.1:20800/admin/init
sleep 1

echo -n "Current leader: "
current_leader 2
echo

echo "Current hash ring: "
curl -s \
     -H 'Content-Type: application/json' \
     http://127.0.0.1:20800/app/hash-ring

echo
echo "Add nodes 3 & 4 as learners"
curl -s \
     -H 'Content-Type: application/json' \
     --data '[3, "127.0.0.1:20803"]' \
     http://127.0.0.1:20800/admin/add-learner
curl -s \
     -H 'Content-Type: application/json' \
     --data '[4, "127.0.0.1:20804"]' \
     http://127.0.0.1:20800/admin/add-learner

echo
echo "Adding nodes 3 & 4 to the cluster"

sleep 1

curl -s \
     -H 'Content-Type: application/json' \
     --data '[0, 1, 2, 3, 4]' \
     http://127.0.0.1:20800/admin/membership

echo
echo -n "Retrieve metrics from node 4:"
curl -s http://127.0.0.1:20804/admin/metrics|jq .

sleep 1

echo "Current hash ring per node 3: "
curl -s \
     -H 'Content-Type: application/json' \
     http://127.0.0.1:20803/app/hash-ring

echo
echo "Killing all nodes..."
kill_all
echo "Killing all nodes...done."
