[package]
name = "tests-support"
version = "0.0.1"
edition = "2024"

[dependencies]
async-trait = { workspace = true }
inventory = { workspace = true }
itertools = { workspace = true }
libtest-mimic = { workspace = true }
serde = { workspace = true, features = ["derive"] }
snafu = { workspace = true }
tap = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread"] }
toml = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }

[[test]]
name = "trivial"
harness = false
