[package]
name = "indielinks-client"
version = "0.0.1"
edition = "2021"

[dependencies]
async-trait = { workspace = true }
bytes = { workspace = true } # RUSTSEC-2026-0007
chrono = { workspace = true, features = ["serde"] }
clap = { workspace = true, features = ["cargo", "env", "wrap_help"] }
futures = { workspace = true }
http = { workspace = true }
indielinks-shared = { workspace = true, features = ["backend"] }
itertools = { workspace = true }
pin-project = { workspace = true }
reqwest = { workspace = true, features = ["json"] }
rpassword = { workspace = true }
secrecy = { workspace = true, features = ["serde"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
serde_urlencoded = { workspace = true }
snafu = { workspace = true }
tap = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "signal", "sync"] }
toml = { workspace = true }
tower = { workspace = true, features = ["buffer", "limit", "retry"] }
tower-http = { workspace = true, features = ["auth", "cors", "request-id", "set-header", "trace"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter", "json"] }
url = { workspace = true, features = ["serde"] }

[[bin]]
name = "indic"
path = "src/main.rs"
